### ISSUE TITLE
Cannot build mill assembly from a release source archive

### ISSUE THREAD

**Issue by rolisv** [com-lihaoyi/Ammonite#1130]
When building assembly from the source tarball:
```bash
$ curl -LO https://github.com/lihaoyi/Ammonite/archive/2.3.8.tar.gz
$ tar -xf 2.3.8.tar.gz
$ cd Ammonite-2.3.8
$ mill 'amm[2.13.3].assembly'
Compiling /home/ro/workspace/github/Ammonite-2.3.8/build.sc
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
os.SubprocessException: CommandResult 128

  os.proc.call(ProcessOps.scala:85)
  ammonite.$file.build.$init$(build.sc:11)
  ammonite.$file.build$.<clinit>(build.sc:40)
```
It looks like `build.sc` expects the source to be in git repo.

Is building from the release archive supported? I could not find any docs on that.

**Comment by sake92** [comment]
What is the use case for this?  
You can just clone this repo and then run that command.

**Comment by NatPRoach** [comment]
Just jumping in here to say one use case for adding support for this would be putting tools on to conda / conda-forge `https://conda-forge.org/` and other similar package / environment managers. As is attempting to build from a release tar ball for a package that uses `mill` to build it will not work since release tar balls are not git repos. And since `conda-forge` requires using release tarballs such that they can be checked vs a `sha256` / `md5` checksum'd this means that tools that use the mill build script to compile themselves at present cannot be distributed on conda-forge.
