### ISSUE TITLE
Ammonite should be able to pipe into programs

### ISSUE THREAD

**Issue by dmacias** [com-lihaoyi/Ammonite#367]
Ammonite should be able to pipe stdout to another program.  I would think the intent would be something to the effect of:

`home/"file1.xml" |% less`

Though the same can be achieved with:

`home/"file1.xml" |> (%less _)`

it doesn't account for programs like pbcopy (mac) that only works via stdin.

**Comment by dmacias** [comment]
@lihaoyi suggested:

> currently the %% shellouts all return a CommandResult which just encapsulates the output. we could make it return something richer that allows two-way communication with the subprocess

**Comment by lihaoyi** [comment]
Ideally, we'd have the returned `CommandResult`, instead of being a frozen representation of the total output of the process, be a live `Process` object we can interact with: reading output, sending input, reading more output, killing, signaling, whatever. We could even leave the existing methods to "read all output" or "read all error" to make the common case convenient, while still leaving open the ability to feed in input and otherwise interact with the running process.

This will require a significant amount of rewriting of `Shellout.scala` but I don't think it's hard in-principle

**Comment by lihaoyi** [comment]
Moot since the EOL of ammonite-ops. OS-Lib has its own way of doing this, where you can specify a `os.proc().call(stdin = ...)` to pipe data between subprocesses or other streaming data sources
