### ISSUE TITLE
sourcecode.File() does not return full path to current script

### ISSUE THREAD

**Issue by eikek** [com-lihaoyi/Ammonite#493]
Hello,
is it possible to obtain the path to the currently running script? The `$0` bash equivalent. I hope I didn't miss it in the configuration, but so far I couldn't find anything related. It's not super important; I'm now using a simple wrapper around `amm` to export an env var which I then use in my scripts.

``` shell
#!/usr/bin/env sh
export AMM_SCRIPT="$1"
exec java -jar -Xmx500m -XX:+UseG1GC $JAVA_OPTS ~/bin/_amm "$@"
```

Maybe ammonite provides this already?

Thank you for this great tool!

**Comment by lihaoyi** [comment]
`sourcecode.File()` should work but doesn't

```scala
$ cat foo.sc
println(sourcecode.File())
$ amm foo.sc
foo.sc
```

It appears to currently give the file name, when it should be giving the entire absolute path.

I think there problem is here:

- https://github.com/lihaoyi/Ammonite/blob/master/amm/interp/src/main/scala/ammonite/runtime/Compiler.scala#L288

Instead of just the file name, we should be passing in the full path to the file. 

If you have some time, clone the repo and poke around and see what happens and maybe you'll be able to fix it =)

**Comment by eikek** [comment]
Thanks for the pointer! I'll take a look next time I have time.

**Comment by lihaoyi** [comment]
Should be fixed by $497

**Comment by timcharper** [comment]
This bug continue to exist in 1.5.1 and 1.7.1
